# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - "darwin"
  - "linux"
  - "windows"
  goarch:
  - "amd64"
archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: binary
    files:
      - LICENSE.txt
      - README.md
checksum:
    name_template: '{{ .ProjectName }}_checksums.txt'
source:
  enabled: false
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '.gitignore'
    - '.goreleaser.yml'
